### ISSUE TITLE
The depth is broken in rendering.

### ISSUE THREAD

**Issue by johndyoung** [mocsarcade/enchiridion#17]
Sometimes spaces are rendered on top of creatures thereby hiding them.

Need some way to establish a z-index hierarchy among entities

![image](https://cloud.githubusercontent.com/assets/3590209/13588339/fcb21d02-e49c-11e5-86fd-b7b8a83135b0.png)

**Comment by johndyoung** [comment]
I tried messing around with `stack` a little bit, but didn't see any results. I was tired and, evidently, insane when I was doing it (judging by what I pushed to my fork lol), so I'm going to try again a little today.

If `stack` doesn't yield anything, I'll try changing the render order (`Game.entities` has `Adventurer` as the first element; coming after all `Space` objects might yield the desired results).

If that doesn't work, I'll start doing crazy things like trying CSS' `transformZ` lol

**Comment by ehgoodenough** [comment]
So the way the `zIndex` works at the moment, is that it equals your `this.position.y * 10 + this.stack`, so it should really only be used to differentiate between entities on the same square, between 0 and 9. I wonder why you're getting the bug? When you make a PR, I'll have a look at it :]

**Comment by johndyoung** [comment]
Yup, it shouldn't be happening because a space's Y-coordinate will always be less than that of the adventurer walking on it. Additionally, I have `Space.stack = 0` and `Adventurer.stack = 5`, so it's pretty weird.

I'm probably gonna try changing the render order first thing when I get home from work.

Funky junk!

**Comment by johndyoung** [comment]
Came home over lunch and tried it, changing the render order worked

I'll include it in my PR later today
